:_content-type: PROCEDURE
:description: You can enable FUSE overlay storage driver for Podman
:keywords: FUSE, overlay, configmap, podman, storage, driver
:navtitle: Enabling FUSE overlay with a configmap
:page-aliases:

[id="enabling-fuse-overlay-with-a-configmap"]
= Enabling FUSE overlay with a Configmap

For the UDI, the configuration file that defines the storage driver is the `/home/user/.config/containers/storage.conf` file.

.`storage.conf`
[source]
----
[storage]
driver = "vfs"
----

Using the FUSE overlay storage driver involves replacing the content of `storage.conf` to the following:

.`storage.conf`
[source]
----
[storage]
driver = "overlay"

[storage.options.overlay]
mount_program="/usr/bin/fuse-overlayfs" <1>
----
<1> The absolute path to the `fuse-overlayfs` binary. The `/usr/bin/fuse-overlayfs` path is the default for UDI.

This can be done manually after starting a workspace, and if the administrator enabled `persistUserHome` in the `CheCluster` custom resource, the `storage.conf` file changes will persist after a workspace restart if the workspace does not use ephemeral storage.

Otherwise, it is possible to update the `/home/user/.config/containers/storage.conf` for all workspaces in your {orch-namespace} by creating a ConfigMap that mounts the updated file. See xref:mounting-configmaps.adoc[].

.Prerequisites

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

* The administrator has enabled access to /dev/fuse by following xref:administration-guide:configuring-fuse.adoc[Configuring FUSE]

* A workspace with the required annotations are by following xref:accessing-fuse.adoc[]

.Procedure

. Apply the ConfigMap that mounts an `/home/user/.config/containers/storage.conf` file in your {orch-namespace}.
+
[source,yaml,subs="+quotes,+attributes,+macros"]
----
kind: ConfigMap
apiVersion: v1
metadata:
  name: fuse-overlay
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: file
    controller.devfile.io/mount-path: /home/user/.config/containers
data:
  storage.conf: |
    [storage]
    driver = "overlay"

    [storage.options.overlay]
    mount_program="/usr/bin/fuse-overlayfs"
----

.Verification steps

. Start the workspace containing the required annotations and verify that the storage driver is `overlay`.
+
[subs="+attributes,+quotes"]
----
$ podman info | grep overlay
----
