:_content-type: CONCEPT
:description: Using the FUSE overlay storage driver for Podman
:keywords: authentication, authenticate, github, gitlab, bitbucket
:navtitle: Using the FUSE overlay storage driver for Podman
:page-aliases:

[id="using-the-fuse-overlay-storage-driver-for-podman"]
= Using the FUSE overlay storage driver for Podman

By default, newly created workspaces that do not specify a devfile will use the Universal Developer Image (UDI).
The UDI contains common development tools and dependencies commonly used by developers.

Podman is included in the UDI, allowing developers to build and push container images from their workspace.

By default, the Podman in the UDI is configured to use the `vfs` storage driver. Since the `vfs` storage driver does not support copy-on-write, changing the storage driver to `overlay` can improve image build times.

To use the FUSE overlay storage driver for Podman in a workspace, there are three requirements:

. The administrator has configured FUSE on the cluster by following xref:administration-guide:configuring-fuse.adoc[Configuring FUSE].
. The workspace has the necessary annotations for using the `/dev/fuse` device. See xref:accessing-fuse.adoc[].
. The `storage.conf` file in the workspace container has been configured to use the FUSE overlay storage driver. See xref:enabling-overlay-with-a-configmap.adoc[].

.Additional resources
* link:https://github.com/devfile/developer-images[Universal Developer Image]
