:navtitle: Using credentials and configurations in workspaces
:keywords: user-guide, configuring, user, configmaps, secrets, volumes, mounting, mount
:page-aliases: 

[id="using-credentials-and-configurations-in-workspaces_{context}"]
= Using credentials and configurations in workspaces

You can use your credentials and configurations in your workspaces:

* Mount your credentials and sensitive configurations as {kubernetes} Secrets to the {devworkspace} containers in the {orch-name} cluster of your organization's {prod-short} instance.

* Mount your non-sensitve configurations as {kubernetes} ConfigMaps to the {devworkspace} containers in the {orch-name} cluster of your organization's {prod-short} instance.

The mounting process uses the standard {kubernetes} mounting mechanism and requires applying additional labels and annotations to your existing resources. Resources are mounted when starting a new workspace or restarting an existing one.

You can create permanent mount points for various components:

* Maven configuration, such as the `settings.xml` file 
* SSH key pairs
* AWS authorization tokens
* Configuration files
* Persistent storage
* Git credentials store files




xref:using-a-git-credentials-store.adoc[your Git credentials store]
other xref:mounting-other-secrets.adoc[Secrets]
xref:mounting-configmaps.adoc[ConfigMaps] into your workspace containers


== Image pull Secrets
You can configure image pull Secrets to be applied to workspace Pods to access container registries requiring authentication. See xref:creating-image-pull-secrets.adoc[Creating image pull Secrets].

.Additional resources

* link:https://kubernetes.io/docs/concepts/configuration/secret/[Kubernetes Documentation: Secrets]
* link:https://kubernetes.io/docs/concepts/configuration/configmap/[Kubernetes Documentation: ConfigMaps]