:_content-type: CONCEPT
:description: Using the FUSE overlay storage driver for Podman
:keywords: authentication, authenticate, github, gitlab, bitbucket
:navtitle: Using the FUSE overlay storage driver for Podman
:page-aliases:

[id="using-the-fuse-overlay-storage-driver-for-podman"]
= Using the FUSE overlay storage driver for Podman

By default, newly created workspaces that do not specify a devfile will use the Universal Developer Image (UDI).
The UDI contains common development tools and dependencies commonly used by developers.

Podman is included in the UDI, allowing developers to build and push container images from their workspace.

By default, the Podman in the UDI is configured to use the `vfs` storage driver. Since the `vfs` storage driver does not support copy-on-write, changing the storage driver to `overlay` can improve image build times.

This document describes how to change the storage driver to `overlay` for Podman running in workspaces with UDI.

.Prerequisites

* The administrator has enabled container access to /dev/fuse by following xref:administration-guide:configuration-fuse.adoc[Administration Guide:Configuring FUSE]

* An active `{orch-cli}` session with administrative permissions to the destination {orch-name} cluster. See {orch-cli-link}.

.Procedure



.Additional resources
* link:https://github.com/devfile/developer-images[Universal Developer Image]