[id="proc_viewing-dev-workspace-operator-metrics-on-grafana-dashboards"]
= Viewing {devworkspace} Operator metrics from an OpenShift web console dashboard

After configuring the in-cluster Prometheus instance to collect {devworkspace} Operator metrics, the metrics can be viewed from a custom dashboard within the `Administrator` perspective of the OpenShift web console.

.Prerequisites

* The in-cluster Prometheus instance is collecting metrics. See xref:proc_collecting-dev-workspace-operator-metrics-with-prometheus[].

.Procedure

. Create a ConfigMap in the `openshift-config-managed` {orch-namespace} containing the dashboard definition. The dashboard definition is based on Grafana 6.x dashboards, however, not all Grafana 6.x dashboard features are supported.
+
[source,terminal,subs="+attributes,quotes"]
----
$ kubectl create configmap grafana-dashboard-dwo \
  --from-literal=dwo-dashboard.json="$(curl https://gist.githubusercontent.com/dkwon17/69af6c4df9da8c0951eb9507e44499ca/raw/26ad275ece7e46f3dc6c25e894b8f130c3d0ebaa/dwo-dashboard.yaml)" \
  -n openshift-config-managed
$ kubectl label configmap grafana-dashboard-dwo console.openshift.io/dashboard=true -n openshift-config-managed
----

.Verification steps

. In the `Administrator` perspective of the OpenShift web console, navigate to `Observe > Dashboards` from the sidebar menu on the left.

. Select the `Dev Spaces Server JVM` dashboard under the `Dashboard` dropdown menu and verify that the dashboard panels contain data.
