[id="ref_devworkspace-specific-metrics_{context}"]
= DevWorkspace-specific metrics

[role="_abstract"]
This section describes the DevWorkspace-specific metrics exposed by the `devworkspace-controller-metrics` service.

.Metrics
,=== 
 Name, Type, Description, Labels 
 
 `devworkspace_started_total`,"Counter","Number of DevWorkspace starting events.", "`source`, `routingclass`" 
 `devworkspace_started_success_total`,"Counter","Number of DevWorkspaces successfully entering the `Running` phase.", "`source`, `routingclass`" 
 `devworkspace_fail_total`,"Counter","Number of failed DevWorkspaces.", "`source`, `reason`" 
 `devworkspace_startup_time`,"Histogram","Total time taken to start a DevWorkspace, in seconds.", "`source`, `routingclass`" 
,=== 

.Labels
,=== 
 Name, Description, Values 
 
 `source`,"The `controller.devfile.io/devworkspace-source` label of the DevWorkspace.",`string` 
 `routingclass`,"The `spec.routingclass` of the DevWorkspace.",`"basic|cluster|cluster-tls|web-terminal"` 
 `reason`,"The workspace startup failure reason.",`"BadRequest|InfrastructureFailure|WorkspaceEngineFailure|Unknown"` 
,=== 